### ISSUE TITLE
Show confirmation after submitting delivery reclamation

### ISSUE THREAD

**Issue by vapaj** [KSF-Media/affresco#266] opened 2020-02-28 06:57 UTC
Instead of just showing the green tick after sending a delivery reclamation, we really should have some confirmation text to show there (as we are not showing the actual created reclamations to the user).

**Comment by ae-mo** [comment] 2020-03-09 10:48
Duplicate of #275

**Comment by ae-mo** [comment] 2020-03-12 15:14
Closed by #276.

**Closed** 2020-03-12 15:16 UTC
Labels: app/mitt-konto
